/** Plain-language explanations shown next to every metric, so a first-time investor is never stuck. */
export const GLOSSARY: Record<string, string> = {
  "Market cap": "Total value of all the company's shares at today's price.",
  "P/E": "Price ÷ earnings per share: how much you pay for each 1 (₹ or $) of yearly profit. Lower can mean cheaper, or that the market expects slower growth.",
  "P/B": "Price ÷ book value per share: how the market values the company against its net assets.",
  "EV/EBITDA": "Enterprise value (market cap + debt − cash) ÷ EBITDA. Useful for comparing companies with different debt levels.",
  "PEG": "P/E ÷ earnings growth rate. Around 1 suggests the price is in line with growth; well above 2 suggests you are paying up.",
  "Dividend yield": "Yearly dividend as a percentage of the share price.",
  ROE: "Return on equity: profit earned on every 100 (₹ or $) that shareholders have in the business. Above 15% is generally considered good.",
  ROCE: "Return on capital employed: profit before interest and tax earned on all capital (equity + debt). Shows how well the business uses its money.",
  "Debt / Equity": "Total borrowings ÷ shareholders' money. Below 0.5 is usually comfortable for non-financial companies.",
  "Operating margin": "Operating profit as a percentage of revenue: how much of every 100 (₹ or $) of sales is left after running costs.",
  "Net margin": "Net profit as a percentage of revenue, after interest and tax.",
  "Cash conversion": "Operating cash flow ÷ net profit. Near or above 1 means reported profits are turning into real cash.",
  "Free cash flow": "Cash from operations minus capital spending: money available to pay dividends, cut debt or reinvest.",
  "Interest coverage": "Operating profit ÷ interest cost. How many times over the company can pay its interest.",
  CAGR: "Compound annual growth rate: the steady yearly growth that would take the first value to the last.",
  "Promoter holding": "Share of the company held by promoters and insiders.",
  EPS: "Earnings per share: net profit divided by the number of shares.",
  GMP: "Grey market premium: an unofficial price at which IPO shares change hands before listing. Not regulated and often wrong.",
  Subscription: "How many times the shares on offer have been applied for. 3x means demand was three times the supply.",
  Volatility: "How much the price swings in a year. Higher means a bumpier ride.",
  Drawdown: "The largest fall from a previous high.",
  // technical indicators (Technicals tab)
  EMA: "Exponential moving average: the average closing price over a period, weighting recent days more. Price above a rising EMA is read as an uptrend.",
  SMA: "Simple moving average: the plain average closing price over a period. The 50 crossing above the 200 is called a golden cross; below, a death cross.",
  RSI: "Relative Strength Index (0-100): the strength of recent gains against recent losses. Above 70 is called overbought, below 30 oversold; strong trends can stay there.",
  MACD: "Moving Average Convergence Divergence: the gap between the 12- and 26-period EMAs, and its 9-period average (signal line). Above the signal line means momentum is improving.",
  Bollinger: "Bollinger Bands: a band 2 standard deviations either side of the 20-period average. Unusually narrow bands (a squeeze) often come before a big move.",
  Supertrend: "A line that trails the price using its average range (ATR). Price above it is read as an uptrend, below as a downtrend; it flips when the trend turns.",
  ADX: "Average Directional Index: how strong a trend is, not its direction. Below 20 means no clear trend, above 25 a strong one. +DI above −DI means the trend is up.",
  Stochastic: "Where the close sits in the recent high-low range (0-100). Above 80 is called overbought, below 20 oversold. %D is a smoothed %K.",
  ATR: "Average True Range: how far the price typically moves in one bar, in rupees (or dollars). Often used to set stop-losses.",
  OBV: "On-Balance Volume: a running total adding volume on up days and subtracting it on down days. It rising with the price confirms the move.",
  VWAP: "Volume-weighted average price for the day. Traders compare the price with it intraday; it restarts every session.",
};
