import type { Metadata } from "next";
import Link from "next/link";
import LegalPage, { Contact, Section } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Use · FinSight" };

export default function Terms() {
  return (
    <LegalPage title="Terms of Use"
      intro="These terms apply when you use FinSight. By using the site or signing in, you agree to them. They are written to be read; the short version is: FinSight helps you research, but investment decisions are yours.">
      <Section title="A research tool, not investment advice">
        <p>
          FinSight provides data, calculations, explanations and AI-generated summaries for research and education.
          Nothing on FinSight is a recommendation to buy, sell or hold any security. FinSight is not registered with SEBI as
          an investment adviser or research analyst. Make your own decisions, and consult a registered adviser if you need
          personal advice.
        </p>
      </Section>

      <Section title="Accuracy of data">
        <p>
          Market and company data comes from third parties, including Yahoo Finance, the National Stock Exchange of India
          (NSE) and company filings. It may be delayed, incomplete or wrong. Scores and scenarios are rule-based calculations,
          not predictions. Verify important figures against the company&apos;s official filings.
        </p>
        <p>
          Grey market premium (GMP) figures come from InvestorGain. GMP is unofficial and unregulated, and often differs from
          the actual listing price.
        </p>
      </Section>

      <Section title="AI features">
        <p>
          AI answers, filing summaries and reports are generated by third-party AI models. FinSight checks figures, quotes and
          calculations against their sources and shows warnings when something can&apos;t be confirmed, but AI output can
          still be wrong or incomplete.
        </p>
        <p>
          AI features require signing in with Google and come with a daily allowance per account. We may change the allowance
          to keep the service available for everyone.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You sign in with your Google account and are responsible for activity under it. We may suspend accounts that abuse
          the service. You can stop using FinSight or ask us to delete your account at any time.
        </p>
      </Section>

      <Section title="Fair use">
        <p>Please don&apos;t:</p>
        <ul>
          <li>Try to get around the AI allowance, for example with multiple accounts or automated requests</li>
          <li>Scrape or bulk-download FinSight&apos;s data or overload the service</li>
          <li>Use FinSight for anything unlawful, or to mislead other people about securities</li>
        </ul>
      </Section>

      <Section title="Availability">
        <p>
          FinSight is provided as it is, without guarantees that it will be available, uninterrupted or error-free. Features
          may change or be removed.
        </p>
      </Section>

      <Section title="Liability">
        <p>
          To the extent the law allows, FinSight is not liable for losses arising from investment decisions made using the
          site, or from errors, delays or gaps in the data or AI output.
        </p>
      </Section>

      <Section title="Governing law">
        <p>These terms are governed by the laws of India.</p>
      </Section>

      <Section title="Changes and contact">
        <p>
          We may update these terms and will change the date at the top when we do. Questions? <Contact />. How we handle personal
          data is described in our <Link href="/privacy" className="text-accent underline">Privacy Policy</Link>.
        </p>
      </Section>
    </LegalPage>
  );
}
